import type { BuildResult } from './client'

export const MOCK_RESULT: BuildResult = {
  decomposition: {
    device: "FPV Racing Drone 5\"",
    description: "A lightweight 5-inch FPV racing drone for competitive and freestyle flying",
    estimated_budget_usd: 285,
    difficulty: "intermediate",
    blocks: [
      {
        name: "Frame",
        purpose: "Structural support for all components",
        components: [
          {
            name: "Carbon Fiber Frame 5\"",
            spec: "3K carbon, 225mm wheelbase, 5mm arms",
            quantity: 1,
            estimated_price_usd: 28,
            why: "Lightweight and durable structure",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 32,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              alternatives: [
                { name: "TBS Source One V5", price_usd: 25, url: "https://amazon.com" },
              ],
            },
          },
        ],
      },
      {
        name: "Propulsion",
        purpose: "Motors and ESC to generate thrust",
        components: [
          {
            name: "Brushless Motor 2306 2400KV",
            spec: "2306 size, 2400KV, 6S compatible",
            quantity: 4,
            estimated_price_usd: 17,
            why: "High thrust-to-weight ratio for racing",
            sourcing: {
              found: true,
              source: "octopart",
              price_usd: 15.5,
              shop_name: "GetFPV",
              shop_url: "https://getfpv.com",
              manufacturer: "EMAX",
              mpn: "ECO II 2306",
              in_stock: true,
              alternatives: [
                { name: "T-Motor F40 Pro IV", price_usd: 22, url: "https://getfpv.com" },
                { name: "iFlight XING2", price_usd: 18, url: "https://iflight.com" },
              ],
            },
          },
          {
            name: "4-in-1 ESC 45A",
            spec: "BLHeli_32, 45A continuous, 6S",
            quantity: 1,
            estimated_price_usd: 42,
            why: "Controls all 4 motors from single board",
            sourcing: {
              found: true,
              source: "lcsc",
              price_usd: 38,
              shop_name: "LCSC",
              shop_url: "https://lcsc.com",
              manufacturer: "SpeedyBee",
              mpn: "BLS-45A-4IN1",
              in_stock: true,
              alternatives: [],
            },
          },
          {
            name: "Propellers 5\" Tri-blade",
            spec: "5140 or 5143, PC material",
            quantity: 8,
            estimated_price_usd: 3,
            why: "Converts motor rotation into thrust (extras for crashes)",
            sourcing: {
              found: true,
              source: "aliexpress",
              price_usd: 2.2,
              shop_name: "AliExpress",
              shop_url: "https://aliexpress.com",
              alternatives: [],
            },
          },
        ],
      },
      {
        name: "Flight Controller",
        purpose: "Brain of the drone — stabilization and control",
        components: [
          {
            name: "Flight Controller F7",
            spec: "STM32F722, gyro ICM42688, OSD",
            quantity: 1,
            estimated_price_usd: 35,
            why: "Processes gyro data and controls motor speed 8000 times per second",
            sourcing: {
              found: true,
              source: "octopart",
              price_usd: 33,
              shop_name: "Mouser",
              shop_url: "https://mouser.com",
              manufacturer: "SpeedyBee",
              mpn: "F405 V4",
              in_stock: true,
              alternatives: [
                { name: "Betaflight F7 AIO", price_usd: 40, url: "https://getfpv.com" },
              ],
            },
          },
          {
            name: "Radio Receiver",
            spec: "ExpressLRS 2.4GHz, ceramic antenna",
            quantity: 1,
            estimated_price_usd: 15,
            why: "Receives commands from your radio transmitter",
            sourcing: {
              found: true,
              source: "tavily",
              price_usd: 12,
              shop_name: "BetaFPV",
              shop_url: "https://betafpv.com",
              alternatives: [],
            },
          },
        ],
      },
      {
        name: "FPV System",
        purpose: "Camera and video transmitter for first-person view",
        components: [
          {
            name: "FPV Camera",
            spec: "1200TVL, CMOS, 2.1mm lens, 16:9",
            quantity: 1,
            estimated_price_usd: 22,
            why: "Captures video for real-time FPV feed",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 20,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              manufacturer: "Caddx",
              mpn: "Ratel2",
              in_stock: true,
              alternatives: [],
            },
          },
          {
            name: "Video Transmitter (VTX)",
            spec: "5.8GHz, 600mW, analog",
            quantity: 1,
            estimated_price_usd: 25,
            why: "Transmits live video to your goggles",
            sourcing: {
              found: true,
              source: "lcsc",
              price_usd: 22,
              shop_name: "LCSC",
              shop_url: "https://lcsc.com",
              manufacturer: "Rush",
              mpn: "Tank Mini",
              in_stock: false,
              alternatives: [
                { name: "AKK X2 Ultimate", price_usd: 18, url: "https://aliexpress.com" },
              ],
            },
          },
        ],
      },
      {
        name: "Power",
        purpose: "Battery and power distribution",
        components: [
          {
            name: "LiPo Battery 6S 1300mAh",
            spec: "22.2V, 100C, XT60 connector",
            quantity: 2,
            estimated_price_usd: 28,
            why: "Powers everything, 2 batteries for continuous flying",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 26,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              manufacturer: "GNB",
              mpn: "GNB 1300 6S",
              alternatives: [
                { name: "CNHL Black 1300mAh", price_usd: 23, url: "https://aliexpress.com" },
              ],
            },
          },
        ],
      },
    ],
  },
  guide: {
    steps: [
      {
        number: 1,
        title: "Assemble the frame",
        what_to_do: "Take the bottom plate and four arms. Slide each arm into the slots on the bottom plate. Secure with the included M3 bolts. Think of it like building with LEGO — each piece clicks into its place.",
        why: "The frame is the skeleton that holds everything together",
        tip: "Tighten bolts in an X-pattern (opposite corners), not clockwise. This distributes pressure evenly.",
        tools_needed: ["Phillips #2 screwdriver", "2.5mm hex key"],
        time_minutes: 10,
      },
      {
        number: 2,
        title: "Mount the motors",
        what_to_do: "Press-fit each motor onto the arm ends. Front-right and back-left get clockwise motors (marked CW). Front-left and back-right get counter-clockwise (CCW). Secure each motor with 4 tiny M3 bolts.",
        why: "Motors spin propellers to create thrust. CW/CCW pairing prevents the drone from spinning",
        tip: "Check rotation direction BEFORE securing. Spin the motor shaft by hand — it should feel smooth.",
        tools_needed: ["2mm hex key", "threadlocker (blue)"],
        time_minutes: 15,
      },
      {
        number: 3,
        title: "Install the ESC stack",
        what_to_do: "Place the 4-in-1 ESC on the frame standoffs. The ESC is the 'power manager' — it controls how fast each motor spins. Connect each motor's 3 wires to the corresponding ESC pads. Solder them securely.",
        why: "The ESC translates brain signals into motor power",
        tip: "If a motor spins the wrong way later, just swap any two of its three wires.",
        tools_needed: ["Soldering iron", "Solder wire", "Flux"],
        time_minutes: 25,
      },
      {
        number: 4,
        title: "Mount the flight controller",
        what_to_do: "Stack the flight controller on top of the ESC using the rubber grommets (vibration dampers). Connect the flat cable from ESC to FC. This is the brain — it reads the gyroscope and tells the ESC what to do.",
        why: "The FC is what keeps the drone stable in the air",
        tip: "Make sure the arrow on the FC points forward — this tells it which direction is 'front'.",
        tools_needed: ["Phillips #2 screwdriver"],
        time_minutes: 10,
      },
      {
        number: 5,
        title: "Install camera and VTX",
        what_to_do: "Mount the FPV camera in the front camera mount. Tilt it 25-30 degrees up — this is your viewing angle when flying forward. Connect camera to VTX, VTX to FC for smart audio control.",
        why: "Camera captures what you see through goggles, VTX transmits it wirelessly",
        tip: "Tilt angle matters: 25° for beginners (more stable view), 35° for racing (faster forward flight).",
        tools_needed: ["Small Phillips screwdriver"],
        time_minutes: 15,
      },
      {
        number: 6,
        title: "Wire the receiver and bind",
        what_to_do: "Solder the ExpressLRS receiver to the FC UART pads. Mount it with double-sided tape, antenna pointing up and back. Put the FC into bind mode, then your transmitter — they should connect within seconds.",
        why: "The receiver is how your radio controller talks to the drone",
        tip: "Keep the antenna away from carbon fiber and metal — it blocks the signal.",
        tools_needed: ["Soldering iron", "Double-sided tape"],
        time_minutes: 15,
      },
      {
        number: 7,
        title: "Configure Betaflight",
        what_to_do: "Connect the FC to your computer via USB. Open Betaflight Configurator. Set motor protocol to DSHOT600, enable RPM filtering, set OSD layout, configure ELRS receiver protocol.",
        why: "Software setup — without this the drone won't fly properly",
        tip: "NEVER connect a battery while USB is plugged in. ALWAYS remove propellers before configuring.",
        tools_needed: ["USB-C cable", "Computer with Betaflight Configurator"],
        time_minutes: 20,
      },
      {
        number: 8,
        title: "Final assembly and maiden flight",
        what_to_do: "Attach propellers (CW props on CW motors, CCW on CCW). Strap the battery with a LiPo strap. Go to an open field, arm the drone, and gently push the throttle up. If it lifts evenly — you built it right!",
        why: "Time to fly what you built",
        tip: "First flight in Angle mode (auto-level). Switch to Acro only when comfortable.",
        tools_needed: ["Radio transmitter", "FPV goggles", "Battery charger"],
        time_minutes: 30,
      },
    ],
    total_time_hours: 2.5,
    tools_list: ["Phillips #2 screwdriver", "2mm hex key", "2.5mm hex key", "Soldering iron", "Solder wire", "Flux", "Threadlocker (blue)", "USB-C cable", "Computer"],
    warnings: [
      "Always disconnect the battery before working on electronics",
      "Never connect USB and battery at the same time",
      "Remove propellers before any configuration — motors can spin unexpectedly",
      "LiPo batteries are fire hazards — never puncture, over-discharge, or overcharge",
    ],
  },
}
