import type { BuildResult } from './client'

export const MOCK_RESULT: BuildResult = {
  decomposition: {
    device: "FPV Racing Drone 5\"",
    description: "A lightweight 5-inch FPV racing drone for competitive and freestyle flying",
    estimated_budget_usd: 285,
    difficulty: "intermediate",
    blocks: [
      {
        name: "Frame",
        purpose: "Structural support for all components",
        components: [
          {
            name: "Carbon Fiber Frame 5\"",
            spec: "3K carbon, 225mm wheelbase, 5mm arms",
            quantity: 1,
            estimated_price_usd: 28,
            why: "Lightweight and durable structure",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 32,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              alternatives: [
                { name: "TBS Source One V5", price_usd: 25, url: "https://amazon.com" },
              ],
            },
          },
        ],
      },
      {
        name: "Propulsion",
        purpose: "Motors and ESC to generate thrust",
        components: [
          {
            name: "Brushless Motor 2306 2400KV",
            spec: "2306 size, 2400KV, 6S compatible",
            quantity: 4,
            estimated_price_usd: 17,
            why: "High thrust-to-weight ratio for racing",
            sourcing: {
              found: true,
              source: "octopart",
              price_usd: 15.5,
              shop_name: "GetFPV",
              shop_url: "https://getfpv.com",
              manufacturer: "EMAX",
              mpn: "ECO II 2306",
              in_stock: true,
              alternatives: [
                { name: "T-Motor F40 Pro IV", price_usd: 22, url: "https://getfpv.com" },
                { name: "iFlight XING2", price_usd: 18, url: "https://iflight.com" },
              ],
            },
          },
          {
            name: "4-in-1 ESC 45A",
            spec: "BLHeli_32, 45A continuous, 6S",
            quantity: 1,
            estimated_price_usd: 42,
            why: "Controls all 4 motors from single board",
            sourcing: {
              found: true,
              source: "lcsc",
              price_usd: 38,
              shop_name: "LCSC",
              shop_url: "https://lcsc.com",
              manufacturer: "SpeedyBee",
              mpn: "BLS-45A-4IN1",
              in_stock: true,
              alternatives: [],
            },
          },
          {
            name: "Propellers 5\" Tri-blade",
            spec: "5140 or 5143, PC material",
            quantity: 8,
            estimated_price_usd: 3,
            why: "Converts motor rotation into thrust (extras for crashes)",
            sourcing: {
              found: true,
              source: "aliexpress",
              price_usd: 2.2,
              shop_name: "AliExpress",
              shop_url: "https://aliexpress.com",
              alternatives: [],
            },
          },
        ],
      },
      {
        name: "Flight Controller",
        purpose: "Brain of the drone — stabilization and control",
        components: [
          {
            name: "Flight Controller F7",
            spec: "STM32F722, gyro ICM42688, OSD",
            quantity: 1,
            estimated_price_usd: 35,
            why: "Processes gyro data and controls motor speed 8000 times per second",
            sourcing: {
              found: true,
              source: "octopart",
              price_usd: 33,
              shop_name: "Mouser",
              shop_url: "https://mouser.com",
              manufacturer: "SpeedyBee",
              mpn: "F405 V4",
              in_stock: true,
              alternatives: [
                { name: "Betaflight F7 AIO", price_usd: 40, url: "https://getfpv.com" },
              ],
            },
          },
          {
            name: "Radio Receiver",
            spec: "ExpressLRS 2.4GHz, ceramic antenna",
            quantity: 1,
            estimated_price_usd: 15,
            why: "Receives commands from your radio transmitter",
            sourcing: {
              found: true,
              source: "tavily",
              price_usd: 12,
              shop_name: "BetaFPV",
              shop_url: "https://betafpv.com",
              alternatives: [],
            },
          },
        ],
      },
      {
        name: "FPV System",
        purpose: "Camera and video transmitter for first-person view",
        components: [
          {
            name: "FPV Camera",
            spec: "1200TVL, CMOS, 2.1mm lens, 16:9",
            quantity: 1,
            estimated_price_usd: 22,
            why: "Captures video for real-time FPV feed",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 20,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              manufacturer: "Caddx",
              mpn: "Ratel2",
              in_stock: true,
              alternatives: [],
            },
          },
          {
            name: "Video Transmitter (VTX)",
            spec: "5.8GHz, 600mW, analog",
            quantity: 1,
            estimated_price_usd: 25,
            why: "Transmits live video to your goggles",
            sourcing: {
              found: true,
              source: "lcsc",
              price_usd: 22,
              shop_name: "LCSC",
              shop_url: "https://lcsc.com",
              manufacturer: "Rush",
              mpn: "Tank Mini",
              in_stock: false,
              alternatives: [
                { name: "AKK X2 Ultimate", price_usd: 18, url: "https://aliexpress.com" },
              ],
            },
          },
        ],
      },
      {
        name: "Power",
        purpose: "Battery and power distribution",
        components: [
          {
            name: "LiPo Battery 6S 1300mAh",
            spec: "22.2V, 100C, XT60 connector",
            quantity: 2,
            estimated_price_usd: 28,
            why: "Powers everything, 2 batteries for continuous flying",
            sourcing: {
              found: true,
              source: "amazon",
              price_usd: 26,
              shop_name: "Amazon",
              shop_url: "https://amazon.com",
              manufacturer: "GNB",
              mpn: "GNB 1300 6S",
              alternatives: [
                { name: "CNHL Black 1300mAh", price_usd: 23, url: "https://aliexpress.com" },
              ],
            },
          },
        ],
      },
    ],
  },
  guide: {
    before_you_start: "Clear a workspace about 2×3 feet. Lay out all components grouped by block. Have good lighting — you'll be working with small connectors. A silicone soldering mat is highly recommended. This build takes about 2.5 hours at intermediate pace. Don't rush the soldering steps.",
    phases: [
      {
        name: "Mechanical Assembly",
        description: "Building the physical structure",
        steps: [
          {
            number: 1,
            title: "Assemble the frame",
            what_to_do: "Take the bottom plate and four arms. Slide each arm into the slots on the bottom plate — they should only fit one way. Secure with the included M3×8mm bolts. Think of it like building with LEGO — each piece clicks into its specific place.",
            why: "The frame is the skeleton that holds everything together. Getting it right means everything else mounts cleanly.",
            difficulty: "easy" as const,
            components_used: ["Carbon Fiber Frame 5\""],
            tools_needed: ["Phillips #2 screwdriver", "2.5mm hex key"],
            wiring: "",
            tip: "Tighten bolts in an X-pattern (opposite corners first), not clockwise. This distributes pressure evenly and prevents warping.",
            common_mistake: "Over-tightening bolts into carbon fiber. Carbon cracks — use firm but not gorilla-strength tightening. If the bolt stops turning, stop.",
            verification: ["All 4 arms are firmly attached with no wobble", "Frame sits flat on a table — no twisting", "All bolt heads are flush with the surface"],
            time_minutes: 10,
            photo_description: "You should see an X-shaped frame with 4 arms extending from a center plate. All bolts are flush. The frame should feel solid with no flex.",
          },
          {
            number: 2,
            title: "Mount the motors",
            what_to_do: "Press-fit each motor onto the arm ends. This is important: front-right and back-left positions get CW (clockwise) motors. Front-left and back-right get CCW (counter-clockwise). Look for the arrow on the motor bell or the label. Secure each with 4 M3×6mm bolts.",
            why: "Motors spin propellers to create lift. The CW/CCW pairing creates balanced torque — without it, the whole drone would spin like a top.",
            difficulty: "moderate" as const,
            components_used: ["Brushless Motor 2306 2400KV"],
            tools_needed: ["2mm hex key", "Threadlocker (blue)"],
            wiring: "",
            tip: "Apply a tiny drop of blue threadlocker (NOT red — red is permanent!) to each motor bolt. Vibration will loosen them without it.",
            common_mistake: "Wrong motor rotation placement. Label each arm position BEFORE mounting: FR=CW, FL=CCW, BR=CCW, BL=CW. Double-check by spinning the bell.",
            verification: ["All 4 motors are mounted with no wobble", "Motor rotation matches: FR=CW, FL=CCW, BR=CCW, BL=CW", "Motor bells spin freely — no grinding or catching"],
            time_minutes: 15,
            photo_description: "4 motors mounted at the end of each arm. Each has 3 wires hanging loose. The motor bells should spin smoothly if you flick them.",
          },
        ],
      },
      {
        name: "Electronics Installation",
        description: "Soldering and connecting the brain",
        steps: [
          {
            number: 3,
            title: "Install and wire the ESC",
            what_to_do: "Place the 4-in-1 ESC on the bottom standoffs of the frame. The ESC is the 'gas pedal controller' — it takes commands from the brain (FC) and adjusts how fast each motor spins. Now solder each motor's 3 wires to the corresponding motor pads on the ESC (M1, M2, M3, M4).",
            why: "The ESC converts digital signals into motor power. It needs to control each motor independently for the drone to balance and steer.",
            difficulty: "hard" as const,
            components_used: ["4-in-1 ESC 45A", "Brushless Motor 2306 2400KV"],
            tools_needed: ["Soldering iron (350°C)", "Solder wire (60/40)", "Flux", "Wire cutters"],
            wiring: "Motor wires → ESC pads: Front-Right motor → M1 pads, Front-Left → M2, Back-Right → M3, Back-Left → M4. Each motor has 3 wires — the order of the 3 wires doesn't matter for now (you can swap two later if rotation is wrong).",
            tip: "Pre-tin both the ESC pads and motor wires before joining them. Apply flux first, then solder. A good joint is shiny and concave, not blobby.",
            common_mistake: "Cold solder joints — the #1 cause of motor disconnection mid-flight. If the joint looks dull/grainy, reheat it. Each joint should take about 3 seconds of iron contact.",
            verification: ["All 12 motor wires are soldered (3 per motor × 4 motors)", "No solder bridges between adjacent pads", "Gentle tug on each wire — none come loose", "ESC is flat on standoffs, no shorts against the frame"],
            time_minutes: 25,
            photo_description: "ESC mounted on bottom standoffs with 12 motor wires neatly soldered. Wires should be trimmed to minimal length to avoid vibration contact.",
          },
          {
            number: 4,
            title: "Stack the flight controller",
            what_to_do: "Place rubber grommets on the standoffs above the ESC. Set the flight controller (FC) on top — this is the brain. It has a gyroscope that reads the drone's orientation 8,000 times per second. Connect the flat ribbon cable or pin header from ESC to FC.",
            why: "The FC processes gyro data, your stick inputs from the radio, and tells the ESC how to adjust each motor — all in milliseconds.",
            difficulty: "moderate" as const,
            components_used: ["Flight Controller F7"],
            tools_needed: ["Phillips #2 screwdriver"],
            wiring: "ESC → FC: Connect via the 8-pin ribbon cable or solder direct. Check the FC pinout diagram for: VBAT+, VBAT-, Current sensor, Motor signals (M1-M4).",
            tip: "The arrow printed on the FC MUST point toward the front of the drone. This tells the gyroscope which way is forward. Wrong orientation = drone flips on takeoff.",
            common_mistake: "Forgetting the rubber grommets. Without vibration damping, the gyro picks up motor vibrations and the drone oscillates violently.",
            verification: ["FC arrow points forward (same direction as the camera will face)", "Rubber grommets installed — FC shouldn't touch metal standoffs directly", "ESC-to-FC connection is secure"],
            time_minutes: 10,
            photo_description: "FC sitting on rubber grommets above the ESC. Arrow pointing forward. Ribbon cable connecting the two boards.",
          },
          {
            number: 5,
            title: "Install camera and video transmitter",
            what_to_do: "Mount the FPV camera in the front tilt mount. Set the angle to 25-30 degrees upward — this determines your forward flight view. Mount the VTX (Video Transmitter) on the rear standoff or with double-sided tape. Connect camera signal wire to VTX input.",
            why: "The camera captures what you see through your goggles. The VTX broadcasts it wirelessly. Together they are your eyes in the sky.",
            difficulty: "moderate" as const,
            components_used: ["FPV Camera", "Video Transmitter (VTX)"],
            tools_needed: ["Small Phillips screwdriver", "Soldering iron"],
            wiring: "Camera → VTX: Yellow wire (video signal) to VTX Video-In. Red wire to VTX 5V. Black wire to VTX GND. VTX → FC: Connect VTX TX pad to an available FC UART RX pad for SmartAudio control.",
            tip: "Camera tilt angle: 25° for beginners (stable, good visibility), 30° for intermediate, 35°+ for racing. You can adjust later.",
            common_mistake: "Mounting the VTX antenna inside the frame or against carbon fiber. Carbon blocks RF signal. Antenna MUST point upward and clear of the frame.",
            verification: ["Camera is centered and at desired tilt angle", "VTX antenna exits the frame and points up", "No loose wires that could contact spinning propellers"],
            time_minutes: 15,
            photo_description: "Camera visible in the front mount, tilted slightly up. VTX mounted in rear with antenna pointing straight up through a zip tie guide.",
          },
          {
            number: 6,
            title: "Wire the radio receiver",
            what_to_do: "Solder the ExpressLRS receiver's 4 wires to the FC: 5V, GND, TX, RX. Mount the receiver on the rear of the frame with double-sided tape. Route the antenna so it points up and backward, away from carbon fiber.",
            why: "The receiver catches signals from your radio transmitter. Without it, you have no control. ExpressLRS uses 2.4GHz with extremely low latency.",
            difficulty: "hard" as const,
            components_used: ["Radio Receiver"],
            tools_needed: ["Soldering iron", "Solder wire", "Double-sided tape"],
            wiring: "Receiver → FC UART: RX pad on receiver → TX pad on FC (UART6 recommended). TX pad on receiver → RX pad on FC. 5V and GND to any available 5V/GND pads. Set UART6 to SerialRX in Betaflight.",
            tip: "ELRS receivers are tiny — the solder pads are small. Use a fine soldering tip and thin solder wire. Flux is your friend.",
            common_mistake: "TX/RX swap — receiver TX goes to FC RX and vice versa. This is counter-intuitive but necessary. TX means 'transmit FROM this device'.",
            verification: ["Receiver LED lights up when FC is powered (should blink fast = waiting to bind)", "Antenna is mounted away from carbon and metal", "Wires are not near motor or propeller paths"],
            time_minutes: 15,
            photo_description: "Small receiver mounted on rear with tape. Thin antenna wire points upward. 4 solder connections to FC are clean.",
          },
        ],
      },
      {
        name: "Software & Configuration",
        description: "Making the brain think correctly",
        steps: [
          {
            number: 7,
            title: "Flash firmware and configure Betaflight",
            what_to_do: "Connect FC to computer via USB-C. Download Betaflight Configurator. Flash latest Betaflight firmware for your FC target. Configure: motor protocol → DSHOT600, receiver protocol → CRSF (for ELRS), enable RPM filtering, set up OSD layout, calibrate accelerometer.",
            why: "Betaflight is the operating system of the drone. Without proper configuration, it won't fly stable — or at all.",
            difficulty: "moderate" as const,
            components_used: ["Flight Controller F7"],
            tools_needed: ["USB-C cable", "Computer with Betaflight Configurator"],
            wiring: "",
            tip: "NEVER connect a LiPo battery while USB is plugged in — this can fry components. ALWAYS remove all propellers before connecting to computer.",
            common_mistake: "Skipping the accelerometer calibration. Place the drone on a perfectly flat surface, go to Setup tab, click 'Calibrate Accelerometer'. Without this, Angle mode won't work correctly.",
            verification: ["Betaflight connects and shows sensor readings (gyro moving = working)", "Motors tab: each motor spins in correct direction (test WITHOUT props!)", "Receiver tab: stick movements show correct channel responses", "OSD shows battery voltage when you connect a LiPo"],
            time_minutes: 20,
            photo_description: "Betaflight Configurator connected, showing the 3D model matching your drone's movements. All status indicators green.",
          },
          {
            number: 8,
            title: "Bind receiver to transmitter",
            what_to_do: "Put your radio transmitter into ELRS bind mode (usually long-press a button). The receiver LED should change from fast blink to solid — that means they're paired. Test all sticks and switches in Betaflight's Receiver tab.",
            why: "Binding creates a secure link between your specific transmitter and receiver. Without it, the drone ignores your commands.",
            difficulty: "easy" as const,
            components_used: ["Radio Receiver"],
            tools_needed: ["Radio transmitter"],
            wiring: "",
            tip: "If binding fails: power cycle both devices, make sure ELRS firmware versions match on transmitter and receiver.",
            common_mistake: "Mismatched ELRS versions between transmitter and receiver modules. Both must run the same major version (e.g., both 3.x).",
            verification: ["Receiver LED is solid (not blinking)", "All 4 stick axes move channels in Betaflight Receiver tab", "Switches trigger aux channels correctly"],
            time_minutes: 10,
            photo_description: "Receiver LED solid. Betaflight Receiver tab showing stick movements mapped to correct channels.",
          },
        ],
      },
      {
        name: "Final Assembly & First Flight",
        description: "Bringing it all together",
        steps: [
          {
            number: 9,
            title: "Attach propellers and final check",
            what_to_do: "Attach CW propellers to CW motors and CCW props to CCW motors — they're marked on the propeller hub. Press-fit firmly. Do a final inspection: wiggle all connectors, check for loose wires, ensure nothing can contact propellers. Strap on a battery with the LiPo strap.",
            why: "Wrong propellers = drone flips. Loose wire = motor cut mid-flight. This final check prevents crashes on maiden flight.",
            difficulty: "easy" as const,
            components_used: ["Propellers 5\" Tri-blade", "LiPo Battery 6S 1300mAh"],
            tools_needed: [],
            wiring: "",
            tip: "Mark your propeller nuts: CW motors get CW-threaded nuts (they self-tighten during flight). Most 5\" props are press-fit — no nuts needed.",
            common_mistake: "Putting CW props on CCW motors. The drone will flip instantly on throttle. Match the arrow on the prop to the motor rotation direction.",
            verification: ["CW props on CW motors, CCW on CCW", "All propellers spin freely without hitting frame or wires", "Battery is secure and balanced (center of gravity near the middle)", "No loose wires anywhere — tuck everything with zip ties"],
            time_minutes: 10,
            photo_description: "Complete drone with all 4 propellers. Battery strapped underneath with velcro strap. Clean build with no visible loose wires.",
          },
          {
            number: 10,
            title: "Maiden flight",
            what_to_do: "Go to an open field (no people, cars, or trees nearby). Put on FPV goggles, power on transmitter first, then plug in the drone battery. Arm the drone (usually both sticks down-in). Gently push throttle up — the drone should lift straight. If it drifts, land and trim in Betaflight.",
            why: "The moment of truth — everything you've built comes together. First flight is the most exciting part.",
            difficulty: "moderate" as const,
            components_used: ["LiPo Battery 6S 1300mAh"],
            tools_needed: ["Radio transmitter", "FPV goggles", "Battery charger"],
            wiring: "",
            tip: "Start in Angle mode (self-leveling). Hover at knee height for 30 seconds. If stable, go higher. Switch to Acro mode only when you're comfortable — it disables auto-level.",
            common_mistake: "Full throttle on first takeoff. Be GENTLE. A 6S drone has insane power — start with 20% throttle and feel it out.",
            verification: ["Drone hovers stable without drifting excessively", "All motors sound smooth (no grinding or stuttering)", "OSD shows battery voltage above 22V (6S fully charged = 25.2V)", "Video feed is clear with no interference"],
            time_minutes: 30,
            photo_description: "Drone hovering steadily about 1 meter off the ground in an open field. All propellers spinning, no visible tilt.",
          },
        ],
      },
    ],
    total_time_hours: 2.5,
    tools_list: ["Phillips #2 screwdriver", "2mm hex key", "2.5mm hex key", "Soldering iron (350°C)", "Solder wire (60/40 or lead-free)", "Flux", "Wire cutters", "Threadlocker (blue)", "Double-sided tape", "Zip ties", "USB-C cable", "Computer with Betaflight Configurator", "Radio transmitter", "FPV goggles"],
    materials_list: ["Solder wire", "Flux paste", "Heat shrink tubing (various sizes)", "Zip ties", "Double-sided tape", "Blue threadlocker", "Electrical tape"],
    safety_warnings: [
      "ALWAYS disconnect the battery before working on electronics",
      "NEVER connect USB and LiPo battery at the same time — this can fry your FC",
      "ALWAYS remove propellers before connecting to computer or testing motors",
      "LiPo batteries are fire hazards — never puncture, over-discharge below 3.3V/cell, or charge unattended",
      "Soldering iron is 350°C — keep away from skin, wires, and LiPo batteries",
    ],
    after_completion: "Congratulations — you built a racing drone from scratch! For the first few flights, keep it in Angle mode and practice hovering. Gradually increase altitude and try gentle turns. After 5-10 packs of comfortable flying, try Acro mode — this is where the real fun begins. Check all bolts and solder joints after every 5 flights. Happy flying!",
  },
}
